### ISSUE TITLE
Files copying even though they exist in destination

### ISSUE THREAD

**Issue by jshatch** [cobbzilla/s3s3mirror#75] opened 2016-06-27 22:45 UTC
Lately it seems all the files in our source bucket are being copied even if they already exist in the destination.  I get this when I run it verbose:

pool-1-thread-10 INFO : org.cobbzilla.s3s3mirror.store.s3.S3FileStore - getObjectMetadata(backup-bucket-79564fd4be,/test/file1) starting....
pool-1-thread-10 INFO : org.cobbzilla.s3s3mirror.store.s3.job.S3KeyCopyJob - shouldTransfer: destination key (/test/file1) exists but ETag differs, checking SHA-256
pool-1-thread-10 INFO : org.cobbzilla.s3s3mirror.store.s3.S3FileStore - getObjectMetadata(prod-bucket-f9ded5bfb9,/test/file1) starting....
pool-1-thread-10 INFO : org.cobbzilla.s3s3mirror.store.s3.job.S3KeyCopyJob - shouldTransfer: destination key (/test/file1) exists but has no SHA-256 hash
pool-1-thread-10 INFO : org.cobbzilla.s3s3mirror.store.s3.job.S3KeyCopyJob - shouldTransfer: destination key (/test/file1) differs from source, return true for key: /test/file1
pool-1-thread-10 INFO : org.cobbzilla.s3s3mirror.store.s3.job.S3KeyCopyJob - copying (try #0): /test/file1 to: /test/file1
pool-1-thread-10 INFO : org.cobbzilla.s3s3mirror.store.s3.S3FileStore - getObjectMetadata(prod-bucket-f9ded5bfb9,/test/file1) starting....
pool-1-thread-10 INFO : org.cobbzilla.s3s3mirror.store.s3.job.S3KeyCopyJob - successfully copied /test/file1 -> /test/file1
pool-1-thread-10 INFO : org.cobbzilla.s3s3mirror.store.s3.job.S3KeyCopyJob - done with /test/file1

I don't know when this started happening but backups went from under 2 hours to over 12.

**Comment by cobbzilla** [comment] 2016-07-30 06:46
Which version of s3s3mirror are you using, and what is the command line you're invoking it with. Feel free to anonymize bucket names and paths.

**Comment by timtrinidad** [comment] 2016-08-05 17:40
This happened to me as well. Check the etags between the source and destination files. 

As an example, my source file had etag "c7dcbb0565aa065e74296c194a2d06e0-2" and my destination has "01a4da2fed4ac3cdfdde8d813ce4a43f" which s3s3mirror will consider as different and recopy. It appears to do with uploading multipart upload operations - in this case the source was uploaded in parts and the destination was not resulting in different etags: http://stackoverflow.com/questions/6591047/etag-definition-changed-in-amazon-s3

We're getting around this by using the -S (--size-only) option which compares file sizes rather than etags.

**Comment by cobbzilla** [comment] 2016-08-10 22:26
Yes, I can confirm that this is a problem with ETags on multi-part files. iirc someone else was working on a fix for this, but it was turning out to be tricky. I would welcome a pull request that addresses this.

**Comment by timor-raiman** [comment] 2017-04-18 14:49
Also affected by this.
The only workaround seems to be disabling ETag comparison (--size-only) or ensuring the multipart upload size is constant among sources and destinations (--upload-part-size).

**Comment by timor-raiman** [comment] 2017-04-18 15:08
A simple solution for a proper subset of usecases would be to modify the objectChanged function to look at sizes and modification dates.
Then, assuming the mirror is never directly modified other than by mirroring the source onto it, ETags don't need to be compared.

The algorithm should check that:
1.	The destination object’s size is equal to the original’s size
2.	The destination object’s last-modified date is greater than or equal to the original’s last-modified date

**Comment by timor-raiman** [comment] 2017-04-19 08:59
This is also apparently the algorithm used by _aws s3 sync_. From its documentation:
```
       The  following  sync command syncs objects under a specified prefix and
       bucket to objects under another specified prefix and bucket by  copying
       s3  objects.   A s3 object will require copying if the sizes of the two
       s3 objects differ, the last modified time of the source is  newer  than
       the  last  modified  time of the destination, or the s3 object does not
       exist under the specified bucket and prefix destination.  In this exam-
       ple,  the  user syncs the bucket mybucket2 to the bucket mybucket.  The
       bucket mybucket contains  the  objects  test.txt  and  test2.txt.   The
       bucket mybucket2 contains no objects:
          aws s3 sync s3://mybucket s3://mybucket2
```
In this case, what is the rationale in using s3s3mirror rather than plain _aws s3 sync_?

**Comment by rfrail3** [comment] 2019-04-09 10:47
Because `s3 sync` needs to enumerate all of the files in the bucket to determine whether a local file already exists in the bucket and if it is the same as the local file, and it is slow with large number of files/folders.

**Closed** 2021-01-20 12:59 UTC
Labels: bug
